### ISSUE TITLE
Getting error while generating adapter from pbjs-java-bidder-generation

### ISSUE THREAD

**Issue by Unnamalai57** [rubicon-project/pbs-java-bidder-generation#1]
Hi,
  I have created new prebid adapter from pbs-java-bidder-generation tool. While generating i get classes with error "The import org.prebid.server.spring.config.bidder.model cannot be resolved"

Can anyone tell me how resolve this issue?

**Comment by RossGoncharuk** [comment]
Hi @Unnamalai57 !

Could you please provide some screenshots and details of this issue? I've tried to generate a files with the tool for latest PBS Java server and both the tool and generated files work fine (tested files in pbs).

1. Please provide a full stack trace for this error.
2. Are you getting it in a Bidder Generation Tool (when generating files) or in Prebid Server Java (while trying to compile with the new files)?
3. Please send a screenshot of a Bidder Generation Tool window with the bidder details that you are entering so I'll try to make the same bidder and see if i get the same error (if any).

Please make sure that you have the latest PBS Java version locally, try again and if the issue remains - provide the above-mentioned information so I'll have a better picture to be able to help you out. Thanks!

**Comment by Unnamalai57** [comment]
I was getting this error when I am getting it from Bidder Generation Tool. And I copied the files to my repository.  And I am also wonder because When I cloned the project from rubicon-project/prebid-server-java to my repository Unnamalai57/prebid-server-java one of the files called org.prebid.server.spring.config.bidder.util were missing. It is ok to show errors in prebid-server-java because the util package were missing. But I dont know why this error occurs in generating tool itself. I have both packages(prebid-server-java and bidder-generation-tool) in a same folder.

**Comment by Unnamalai57** [comment]
Sorry @RossGoncharuk  It was my mistake because org.prebid.server.spring.config.bidder.util package was missing in my repository. But the error occurs when generating files. I have both package bidder-generation-tool and prebid-server-java  are in the same folder.

**Comment by RossGoncharuk** [comment]
@Unnamalai57 Please provide an error stack trace and/or a screenshot of when this issue occurs.

**Comment by Unnamalai57** [comment]
![prebiderror](https://user-images.githubusercontent.com/49053809/58555271-a59ebf80-8236-11e9-8367-9a0c8cbbec0b.png)

**Comment by RossGoncharuk** [comment]
@Unnamalai57 is it where the files are placed on your system after being generated? Because if your /folder/pbs-java-bidder-generation and /folder/prebid-server-java are in the same directory (in my example /folder) - the files generated by BGT should appear in prebid-server-java directory. Works both on Ubuntu and Windows.

Please move the newly generated files into PBS directory and let me know if the problem remains.

**Comment by Unnamalai57** [comment]
@RossGoncharuk when I copied the generated files by BGT to PBS directory the errors were resolved.
